import type { Metadata } from "next";
import { CartProvider } from "@/app/Context/CartContext";

import "./globals.css";
import Navbar from "./_components/Navbar";
import localFont from "next/font/local";
import QueryProvider from "./Context/QueryProvider";

export const metadata: Metadata = {
  title: "Royal Gang",
  description: "Generated by create next app",
};

const heleveticaNeue = localFont({
  src: [
    {
      path: "../app/fonts/helveticaNeue/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../app/fonts/helveticaNeue/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../app/fonts/helveticaNeue/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../app/fonts/helveticaNeue/HelveticaNeueBlack.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white antialiased ${heleveticaNeue.className} scrollbar`}
      >
        <QueryProvider>
          <Navbar />
          <CartProvider>{children}</CartProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
